import { v4 as uuidv4 } from 'uuid';
import { db } from '../db/index.js';
import { reports } from '../db/schema.js';

export interface ScrapeData {
  price?: string | string[];
  features?: string[];
  name?: string | string[];
  raw?: Record<string, unknown>;
  url?: string | string[];
  scrapedAt?: string;
  [key: string]: unknown;
}

export interface Report {
  id: string;
  competitorId: string;
  scrapeId: string;
  htmlContent: string;
  jsonData: ScrapeData;
  isPublic: boolean;
  createdAt: Date;
}

export async function generateReport(
  competitorId: string,
  scrapeId: string,
  data: ScrapeData
): Promise<Report> {
  const id = uuidv4();
  const now = new Date();
  
  // Generate HTML report
  const htmlContent = generateHtmlReport(data);
  
  // Store report
  await db.insert(reports).values({
    id,
    competitorId,
    scrapeId,
    htmlContent,
    jsonData: JSON.stringify(data),
    isPublic: false,
    createdAt: now,
  });
  
  return {
    id,
    competitorId,
    scrapeId,
    htmlContent,
    jsonData: data,
    isPublic: false,
    createdAt: now,
  };
}

function generateHtmlReport(data: ScrapeData): string {
  const features = data.features || [];
  const price = (data.price as string) || 'Not found';
  const name = (data.name as string) || 'Unknown';
  const url = (data.url as string) || '';
  
  return `<!DOCTYPE html>
<html lang="en">
<head>
  <meta charset="UTF-8">
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
  <title>Competitor Report - ${escapeHtml(name)}</title>
  <style>
    * { margin: 0; padding: 0; box-sizing: border-box; }
    body {
      font-family: -apple-system, BlinkMacSystemFont, 'Segoe UI', Roboto, sans-serif;
      line-height: 1.6;
      color: #1f2937;
      background: #f9fafb;
      padding: 2rem;
    }
    .container {
      max-width: 800px;
      margin: 0 auto;
      background: white;
      border-radius: 16px;
      box-shadow: 0 4px 6px rgba(0,0,0,0.1);
      padding: 2rem;
    }
    .header {
      border-bottom: 2px solid #e5e7eb;
      padding-bottom: 1rem;
      margin-bottom: 2rem;
    }
    .logo {
      font-size: 1.5rem;
      font-weight: 700;
      color: #2563eb;
      margin-bottom: 0.5rem;
    }
    .competitor-name {
      font-size: 2rem;
      font-weight: 700;
      margin-bottom: 0.5rem;
    }
    .url {
      color: #6b7280;
      font-size: 0.9rem;
    }
    .section {
      margin-bottom: 2rem;
    }
    .section-title {
      font-size: 1.25rem;
      font-weight: 600;
      margin-bottom: 1rem;
      color: #1f2937;
    }
    .price {
      font-size: 2.5rem;
      font-weight: 700;
      color: #10b981;
    }
    .features {
      list-style: none;
    }
    .features li {
      padding: 0.75rem 0;
      border-bottom: 1px solid #e5e7eb;
    }
    .features li:last-child {
      border-bottom: none;
    }
    .footer {
      margin-top: 2rem;
      padding-top: 1rem;
      border-top: 2px solid #e5e7eb;
      text-align: center;
      color: #6b7280;
      font-size: 0.875rem;
    }
    .badge {
      display: inline-block;
      padding: 0.25rem 0.75rem;
      background: #dbeafe;
      color: #1d4ed8;
      border-radius: 9999px;
      font-size: 0.75rem;
      font-weight: 600;
    }
  </style>
</head>
<body>
  <div class="container">
    <div class="header">
      <div class="logo">📊 Competitor Monitor</div>
      <h1 class="competitor-name">${escapeHtml(name)}</h1>
      <div class="url">${escapeHtml(url)}</div>
      <span class="badge">Generated ${new Date().toLocaleDateString()}</span>
    </div>
    
    <div class="section">
      <h2 class="section-title">💰 Pricing</h2>
      <div class="price">${escapeHtml(price)}</div>
    </div>
    
    ${features.length > 0 ? `
    <div class="section">
      <h2 class="section-title">✨ Features</h2>
      <ul class="features">
        ${features.map(f => `<li>${escapeHtml(f)}</li>`).join('')}
      </ul>
    </div>
    ` : ''}
    
    <div class="footer">
      Generated by <strong>Competitor Monitor</strong> • Know what your competitors are doing
    </div>
  </div>
</body>
</html>`;
}

function escapeHtml(text: string): string {
  return text
    .replace(/&/g, '&amp;')
    .replace(/</g, '&lt;')
    .replace(/>/g, '&gt;')
    .replace(/"/g, '&quot;')
    .replace(/'/g, '&#039;');
}
